version: '3.4'

services:
  client:
    build: client
    volumes:
      - /app/node_modules
      - ./client:/app
    env_file: .env
    ports:
      - 3000
        
  api-swapi:
    build: api-swapi
    env_file: .env
    volumes:
      - /app/node_modules
      - ./api-swapi:/app
    ports:
      - 3000

  api-user:
    build: api-user
    env_file: .env
    volumes:
      - /app/node_modules
      - ./api-user:/app
    ports:
      - 3000

  nginx:
    build: nginx
    container_name: nginx
    restart: 'on-failure'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/html:/etc/nginx/html
    depends_on:
      - api-swapi
      - client
    ports:
      - 80:80
      - 443:443